### ISSUE TITLE
Absolute include

### ISSUE THREAD

**Issue by peci1** [ADVRHumanoids/point_cloud2_filters#2]
https://github.com/torydebra/point_cloud2_filters/blob/1cc996bce2d8dcd261a73e14e7d496b75c48acbf/include/point_cloud2_filters/PassThroughFilterPointCloud2.hpp#L6

This is veeery bad for code reusability. Did you have any problems including `filter_base.hpp` in the standard way?

**Comment by torydebra** [comment]
Yep this is terrible :D I had some problems and then forgot about it.
