### ISSUE TITLE
License

### ISSUE THREAD

**Issue by peci1** [ADVRHumanoids/point_cloud2_filters#3]
I see you licensed this package as GPLv3. This is unusual in ROS ecosystem, where most of the code is under the much more permissive BSD-3 license. Of course the decision about licensing is yours. I just wanted to point to it being unusual, potentially limiting its use by the community.

**Comment by torydebra** [comment]
Usually I like the "open source forcing" of the GPL, but since this is ROS, I will follow the community :D. 
Changed as suggested thanks!
