### ISSUE TITLE
intensity based filter ?

### ISSUE THREAD

**Issue by Arthav24** [ADVRHumanoids/point_cloud2_filters#6]
Hey, is there way to filter PointCloud2 data based on intensities ?
Laser_filters does have one for LaserScan.

**Comment by torydebra** [comment]
I do not remeber where (and really if) I saw this, but you can try with the `PassThroughFilterPointCloud2` setting the `filter_field_name` to "intensity". 

At the moment I can not find a list with all the available `filter_field_name` values or where this is used in PCL to understand if this is doable

**Comment by Arthav24** [comment]
On setting filter_field_name to "intensity" it throws error from PCL.
```Unable to find field name in point type```

I looked into PCL (https://github.com/PointCloudLibrary/pcl/blob/pcl-1.13.1/filters/src/passthrough.cpp) it has only for x/y/z

**Comment by torydebra** [comment]
Have you tried listing the fields available with something like the `getFieldsList` method?https://github.com/PointCloudLibrary/pcl/blob/b3a7428534ba307f40bf7e409d4cc56bb818b907/common/include/pcl/common/io.h#L110

**Comment by Arthav24** [comment]
```x y z intensity t reflectivity ring ambient range```
Got these from the method.
still getting the same.
Interestingly in RAW data i can see fields/channel names as ```x y z intensity t reflectivity ring ambient range``` in rviz as well as from method. but in processed output could only see ```x y z```
